Repository YajingLiu2357/robocodeFall2024, pull requests merged in 2024-11, with the labels that each got.

#35 Merge with upstream
  .github/ISSUE_TEMPLATE/Removing Software Clones.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  robocode.api/src/main/java/gl4java/GLFunc.java
  robocode.api/src/main/java/net/sf/robocode/io/FileUtil.java
  robocode.api/src/main/java/net/sf/robocode/serialization/RbSerializer.java
  robocode.api/src/main/java/robocode/AdvancedRobot.java
  robocode.api/src/main/java/robocode/Event.java
  robocode.api/src/main/java/robocode/ScannedRobotEvent.java
  robocode.battle/src/main/java/net/sf/robocode/battle/BaseBattle.java
  robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
  robocode.battle/src/main/java/net/sf/robocode/battle/Module.java
  robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
  robocode.battle/src/main/java/net/sf/robocode/recording/RecordManager.java
  robocode.repository/src/main/java/net/sf/robocode/repository/items/RepositoryItem.java
  robocode.repository/src/main/java/net/sf/robocode/repository/items/RobotItem.java
  robocode.repository/src/main/java/net/sf/robocode/repository/parsers/ClasspathFileParser.java
  robocode.repository/src/main/java/net/sf/robocode/repository/root/handlers/JarHandler.java
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/CompilerPreferencesDialog.java
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/CompilerProperties.java
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/CompoundUndoManager.java
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/EditWindow.java
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/EditorPane.java
  robocode.ui.editor/src/main/java/net/sf/robocode/ui/editor/JavaDocument.java
Labels: Group 11

#40 #39 Eliminate Code Duplication in RobotPeer.java (lines 806 & 1730)
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
Labels: Group 11, Removing Software Clones

#41 #37 Extracts duplicate codes from checkWallCollision and checkSentryOutsideBorder
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
Labels: Group 11, Removing Software Clones

#42 Clone 1 Type resolved. issue #36.
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
Labels: Removing Software Clones

#44 Eliminate Code Duplication in Battle.java (lines 665 & 686)
  robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
Labels: Group 11, Removing Software Clones

#45 Eliminate Code Duplication in RobotPeer.java (lines 1270 & 1288)
  robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
Labels: Group 11, Removing Software Clones

#48 #47 Removed Directory Traversal attack vulnerabilities.
  robocode.host/src/main/java/net/sf/robocode/host/io/RobotFileSystemManager.java
Labels: Group 11, Remove Software Vulnerabilities

#50 Fixed Directory Traversal attack in ‎robocode.repository/JarExtractor.java
  robocode.repository/src/main/java/net/sf/robocode/repository/packager/JarExtractor.java
Labels: Group 11, Remove Software Vulnerabilities

#52 Specify a secure directory when creating a new temporary file
  robocode.battle/src/main/java/net/sf/robocode/recording/RecordManager.java
Labels: Group 11, Remove Software Vulnerabilities
